// Generated by CoffeeScript 1.5.0
(function() {
  var browser, shopping, wd;

  shopping = 'http://www.google.com/shopping';

  wd = require('wd');

  browser = wd.remote('localhost', 8910);

  this.best_price = function(model, result) {
    return browser.chain().init().get(shopping).title(result).quit();
  };

}).call(this);
