// Generated by CoffeeScript 1.4.0
(function() {

  require('../utils/mongoose');

  this.Coupon = mongoose.model('Coupon', new mongoose.Schema({
    title: String,
    pic: String,
    location: String,
    description: String,
    price: Number
  }));

}).call(this);
