// Generated by CoffeeScript 1.4.0
(function() {
  var Coupon;

  Coupon = require('../../domain/coupon').Coupon;

  app.get("/coupons", function(req, res) {
    return Coupon.find(function(err, coupons) {
      return res.send(coupons);
    });
  });

}).call(this);
