// Generated by CoffeeScript 1.5.0
(function() {

  global.express = require('express');

  global.app = express();

  require('./config');

  app.listen(settings.port);

  console.log("running on " + settings.port);

}).call(this);
