// Generated by CoffeeScript 1.5.0
(function() {
  var assets, pub, routes, views;

  assets = require('connect-assets');

  require('../settings');

  pub = __dirname + '/public';

  views = __dirname + '/views';

  app.configure(function() {
    this.use(assets({
      src: pub
    }));
    this.use(express["static"](pub));
    this.use(express.bodyParser());
    this.use(express.methodOverride());
    this.use(this.router);
    this.set('views', views);
    return this.set('view engine', 'jade');
  });

  routes = require('./routes');

  app.get('/', routes.index);

  app.get('/partials/:name', routes.partials);

  app.get('/api/:op/:pid', routes.getProductBPI);

  app.get('*', routes.index);

}).call(this);
