// Generated by CoffeeScript 1.5.0
(function() {
  var setting;

  setting = function(name, value) {
    return process.env[name] || value;
  };

  global.settings = {
    port: setting('PORT', 3000),
    db_port: setting('DB_PORT', 27017),
    db_server: setting('DB_Server', 'localhost')
  };

  settings.db = "" + settings.db_server + ":" + settings.db_port;

}).call(this);
