// Generated by CoffeeScript 1.5.0
(function() {

  this.index = function(req, res) {
    return res.render('index');
  };

  this.partials = function(req, res) {
    var name;
    name = req.params.name;
    return res.render('partials/' + name);
  };

  this.getProductBPI = function(req, res) {
    var model, op, shopmania, _;
    op = req.params.op;
    model = req.params.pid;
    shopmania = require('../../spiders/shopmania');
    _ = require('underscore');
    return shopmania.best_price(model, function(err, fetchedInfo) {
      var minPriceInfo;
      minPriceInfo = {
        ok: false,
        info: []
      };
      fetchedInfo = _.filter(fetchedInfo, function(item) {
        return item.itemPrice && item.shippingPrice;
      });
      if (fetchedInfo.length > 0) {
        _.map(fetchedInfo, function(item) {
          var match;
          match = String(item.itemPrice).match(/\d+,*\d+/);
          if (match) {
            item.itemPrice = parseFloat(match[0].replace(',', '.'));
          }
          match = String(item.shippingPrice).match(/\d+,*\d+/);
          if (match) {
            item.shippingPrice = parseFloat(match[0].replace(',', '.'));
          }
          return item.source = 'ShopMania.es';
        });
        minPriceInfo.info.push(_.min(fetchedInfo, function(item) {
          return item.itemPrice + item.shippingPrice;
        }));
        minPriceInfo.ok = true;
      }
      return res.json(minPriceInfo);
    });
  };

}).call(this);
